### ISSUE TITLE
Missing windows wheels for Python 3.9

### ISSUE THREAD

**Issue by cdiener** [symengine/symengine.py#341] opened 2021-03-12 20:38 UTC
It seems there are no wheels for symengine and Python 3.9 on PiPy: https://pypi.org/project/symengine/#files.

**Comment by isuruf** [comment] 2021-03-12 20:39
Duplicate of https://github.com/symengine/symengine-wheels/issues/2. We are working on a new release (0.7.0) which will include python 3.9 wheels.

**Closed by isuruf** 2021-03-12 20:39 UTC
