### ISSUE TITLE
Eulers Formula

### ISSUE THREAD

**Issue by BlackTeaAndCoffee** [symengine/symengine.py#225] opened 2018-04-05 10:24 UTC
Hi,

symengine seems not to recognize eulers formula as in e**(ix) = cos(x) + i*sin(x), or cos(x) = (e**(i*x) + e**(ix))/2. The following code should give zero, but it doesn't. 

Analytically in my calculations the complex parts would disappear, here unfortunately symengine doesn't see this.
  
```
from symengine import I 
import symengine as si
r =si.symarray('r', 1)

b =  (si.exp(1.0*I*r[0]) + si.exp(-1.0*I*r[0]))/2 - si.cos(r[0])
print(b)
```
This gives the following
```
(1/2)*(exp((-0.0 - 1.0*I)*r_0) + exp((0.0 + 1.0*I)*r_0)) - cos(r_0)
```

I can go around this by taking the absolute value later on, but maybe there is a better solution. 

Thanks for the help!
BlackTea

**Comment by isuruf** [comment] 2018-04-05 16:04
Duplicate of https://github.com/symengine/symengine/issues/1330

**Closed by isuruf** 2018-04-05 16:04 UTC
