### ISSUE TITLE
Incorrect parsing of y*pow(x, -1)

### ISSUE THREAD

**Issue by FFroehlich** [symengine/symengine.py#251] opened 2018-10-04 19:54 UTC
`symengine.sympify('y*pow(x, -1)')`

evaluates to 

`-1 + y/x`

which is evidently wrong.

I am not sure whether this is the right place to report this problem as my previous report regarding improper parsing (#241) did not receive any feedback. If this problem is not related to the python wrapper and I should report this in the C++ repository, please let me know.

**Comment by isuruf** [comment] 2018-10-04 19:57
Duplicate of https://github.com/symengine/symengine/issues/1444
Will be fixed when https://github.com/symengine/symengine/pull/1211 is merged.

**Closed by isuruf** 2018-10-04 19:57 UTC
