### ISSUE TITLE
py.test errors

### ISSUE THREAD

**Issue by rwst** [symengine/symengine.py#32] opened 2015-12-13 07:58 UTC
I get with master and `py.test -v`:
(from 15 files)

```
___________________ ERROR collecting symengine/tests/test_var.py ___________________
import file mismatch:
imported module 'symengine.tests.test_var' has this __file__ attribute:             
  /usr/lib64/python2.7/site-packages/symengine/tests/test_var.py                    
which is not the same as the test file we want to collect:                          
  /home/ralf/symengine.py/symengine/tests/test_var.py                               
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules                                                                           
```

and after that:

```
***
*** Warning! The following Teuchos::RCPNode objects were created but have
...
  0: RCPNode (map_key_void_ptr=0x3aee840)
       Information = {T=SymEngine::Symbol, ConcreteT=SymEngine::Symbol, p=0x3aee840, has_ownership=1}
       RCPNode address = 0x3b23090
       insertionNumber = 1427
  1: RCPNode (map_key_void_ptr=0x3af0160)
       Information = {T=SymEngine::Symbol, ConcreteT=SymEngine::Symbol, p=0x3af0160, has_ownership=1}
       RCPNode address = 0x3b223c0
       insertionNumber = 8433
...
 16: RCPNode (map_key_void_ptr=0x3aeeb40)
       Information = {T=SymEngine::Symbol, ConcreteT=SymEngine::Symbol, p=0x3aeeb40, has_ownership=1}
       RCPNode address = 0x3b226e0
       insertionNumber = 8469
...
```

**Comment by isuruf** [comment] 2015-12-13 08:58
@rwst, to run tests with `py.test` you have to use `py.test -v symengine/tests/test_*.py` from the root. I forgot about giving the test files when mentioning `py.test`. 

Memory leaks are a duplicate of symengine/symengine#507.
First 16 leaks are due to `var` injecting into global namespace.
Last leak is a new one. I'll check on it.

**Comment by rwst** [comment] 2015-12-13 09:11
OK with the files given everything passes. Close?

**Comment by rwst** [comment] 2016-07-06 06:52
See also https://github.com/symengine/symengine.py/issues/78

**Comment by isuruf** [comment] 2016-07-06 06:54
These leaks appear to be from sympy caching mechanism and #78 is because of global variables as you said.

**Comment by isuruf** [comment] 2017-09-30 22:28
Most of this issue was fixed except https://github.com/symengine/symengine.py/issues/197

**Closed by isuruf** 2017-09-30 22:28 UTC
